### ISSUE TITLE
Confirm OAuth Authentication works with JIRA Cloud?

### ISSUE THREAD

**Issue by kylecordes** [floralvikings/jira-connector#14] opened 2015-09-26 21:56 UTC
Hello; I am stuck at the "oauth_problem=signature_invalid", trying to connect with JIRA Cloud. Before I spend hours digging in, can someone confirm that floralvikings/jira-connector (and really, the OAuth module underneath) works correctly with JIRA Cloud?

**Comment by floralvikings** [comment] 2015-09-28 00:10
I can confirm (at least, as of a few months ago); OnDemand is the platform I tested it on.  I seem to remember seeing that error when testing, but I can't remember what specifically was the cause of it.  I have a hunch that you might be missing the verifier code provided by Jira when requesting an OAuth token, but I'm not 100% sure.

Are you following the process outlined in the [OAuth section](https://github.com/floralvikings/jira-connector#oauth-authentication) of the Readme?  If that process isn't clear enough I can make a few changes, maybe include some screenshots of how Jira responds.

**Comment by kylecordes** [comment] 2015-09-28 01:15
Excellent. Thank you. I will provide an update (or perhaps a document pull request) later, hopefully with notes helpful to the next person to come along.

**Comment by Duologic** [comment] 2015-12-09 19:35
I have Oauth working here, with this change: https://github.com/floralvikings/jira-connector/pull/23

**Comment by floralvikings** [comment] 2016-03-31 23:21
@kylecordes did you ever get it working?  I'm going to close this for now, but if you're still having issues I'll reopen and we can try to figure it out.

**Closed by floralvikings** 2016-03-31 23:21 UTC

**Comment by kylecordes** [comment] 2016-04-01 00:59
Yes, we get everything up and running, this and far more. Thanks again.
