### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by alexcotoranu** [floralvikings/jira-connector#3] opened 2015-05-27 18:59 UTC
Hi, I'm getting the following error on every API call:

![image](https://cloud.githubusercontent.com/assets/12387209/7844626/995e3edc-0466-11e5-8753-2c9c64046047.png)

(This is when running console.log(err); )
I'm connecting to Jira v6.4.1 using basic authentication.

When already logged in the browser, I can get to the API to give me data in the browser with both the IP and the host name of the Jira server.

When logged out I get {"errorMessages":["No project could be found with key 'PROJ'."],"errors":{}} where 'PROJ' would be the project key. This part makes sense as I am not logged in. However, this is not returned to my application when I make the API calls using jira-connector (at least not visibly to me).

Also, I can connect just fine with curl using the first command outlined here: https://developer.atlassian.com/jiradev/api-reference/jira-rest-apis/jira-rest-api-tutorials/jira-rest-api-example-basic-authentication

Any help with this issue would be greatly appreciated.

**Comment by apla** [comment] 2015-08-01 09:54
Have same issue.

`protocol: "http"` fixed issue for me

**Comment by floralvikings** [comment] 2015-08-01 22:34
I haven't been able to reproduce this, but since changing the protocol to HTTP seems to help, I think I might know the problem;  Are the servers you're connecting to using unsigned SSL certificates?  I'm not sure how ```request``` handles those, so that might be the issue.

**Comment by apla** [comment] 2015-08-01 22:38
I just installed jira and at this time I'm waiting right certificate from admins. So, jira is listening on 80 only. When I supply only `host` and `basicAuth`, I see ECONNREFUSED

**Comment by floralvikings** [comment] 2015-09-22 21:42
I'm going to go ahead and close this; the only way I've been able to reproduce it is to disable SSL and then try to connect over https, which obviously isn't going to work.  If this issue persists I'll continue to investigate

**Closed by floralvikings** 2015-09-22 21:42 UTC
